"""Project-level state: Nim dependencies declared in pyproject.toml.

Dependencies live in ``[tool.nimlang] dependencies`` as nimble requirement
strings (``"nimpy"``, ``"nimpy >= 0.2.0"``, ``"nimpy#head"``). Atlas resolves
them into ``.nimlang/deps`` next to pyproject.toml, and the resolved commits are
recorded in ``nimlang.lock`` so every checkout and build gets the same code.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from pathlib import Path

import tomlkit

from nimlang._toolchain import NimlangError, atlas_exe, nim_home

STATE_DIR = ".nimlang"
LOCK_FILE = "nimlang.lock"
LOCK_VERSION = 1
# Atlas works on a nimble file; nimlang generates one from [tool.nimlang].
MANIFEST = "nimlang_deps.nimble"


def find_root(start: Path | None = None) -> Path | None:
    """Closest directory at or above ``start`` holding a pyproject.toml."""
    here = (start or Path.cwd()).resolve()
    for folder in (here, *here.parents):
        if (folder / "pyproject.toml").is_file():
            return folder
    return None


def workspace(root: Path) -> Path:
    return root / STATE_DIR


def dep_name(requirement: str) -> str:
    """``"nimpy >= 0.2"`` -> ``"nimpy"``; also handles ``pkg#rev``, ``pkg@#rev`` and URLs."""
    req = requirement.strip()
    if "://" in req:
        req = req.rstrip("/").rsplit("/", 1)[-1].removesuffix(".git")
    return re.split(r"[\s@<>=~^#]", req, maxsplit=1)[0].lower()


def nimble_requirement(requirement: str) -> str:
    """Requirement in .nimble file syntax; accepts nimble's command-line ``pkg@spec`` form too.

    ``"nimpy@#head"`` -> ``"nimpy#head"``, ``"nimpy@0.2.0"`` -> ``"nimpy == 0.2.0"``.
    """
    req = requirement.strip()
    if "://" in req or "@" not in req:
        return req
    name, _, spec = req.partition("@")
    spec = spec.strip()
    if spec.startswith("#"):
        return f"{name}{spec}"
    if spec[:1] in "<>=~^":
        return f"{name} {spec}"
    return f"{name} == {spec}"


def _load(root: Path) -> tomlkit.TOMLDocument:
    return tomlkit.parse((root / "pyproject.toml").read_text(encoding="utf-8"))


def read_deps(root: Path) -> list[str]:
    tool = _load(root).get("tool", {})
    return [str(d) for d in tool.get("nimlang", {}).get("dependencies", [])]


def write_deps(root: Path, deps: list[str]) -> None:
    doc = _load(root)
    tool = doc.setdefault("tool", tomlkit.table(is_super_table=True))
    section = tool.setdefault("nimlang", tomlkit.table())
    array = tomlkit.array()
    array.extend(deps)
    if len(deps) > 1:
        array.multiline(True)
    section["dependencies"] = array
    (root / "pyproject.toml").write_text(tomlkit.dumps(doc), encoding="utf-8")


def add_deps(root: Path, requirements: list[str]) -> list[str]:
    """Add or replace requirements (matched by package name); returns the new list."""
    deps = read_deps(root)
    for req in requirements:
        name = dep_name(req)
        deps = [d for d in deps if dep_name(d) != name] + [req.strip()]
    write_deps(root, deps)
    return deps


def remove_deps(root: Path, names: list[str]) -> list[str]:
    drop = {dep_name(n) for n in names}
    deps = [d for d in read_deps(root) if dep_name(d) not in drop]
    write_deps(root, deps)
    return deps


def _read_lock(root: Path) -> dict | None:
    path = root / LOCK_FILE
    if not path.is_file():
        return None
    return tomlkit.parse(path.read_text(encoding="utf-8")).unwrap()


def _write_lock(root: Path, requires: list[str], packages: list[dict]) -> None:
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by nimlang from [tool.nimlang] in pyproject.toml. Do not edit."))
    doc.add(tomlkit.comment("Run `nimlang lock` to resolve the dependencies again."))
    doc["version"] = LOCK_VERSION
    array = tomlkit.array()
    array.extend(requires)
    doc["requires"] = array
    tables = tomlkit.aot()
    for pkg in packages:
        tables.append(tomlkit.item(pkg))
    doc["package"] = tables
    (root / LOCK_FILE).write_text(tomlkit.dumps(doc), encoding="utf-8")


def _prepare_workspace(root: Path, deps: list[str]) -> Path:
    folder = workspace(root)
    folder.mkdir(parents=True, exist_ok=True)
    gitignore = folder / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text("*\n")
    lines = [f"requires {json.dumps(nimble_requirement(d))}" for d in deps]
    (folder / MANIFEST).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return folder


def run_atlas(root: Path, args: list[str]) -> int:
    """Run the bundled atlas in the project's workspace.

    The real compiler goes first on PATH: atlas asks it for its version, and
    nothing it runs needs a C compiler.
    """
    env = dict(os.environ)
    env["PATH"] = os.pathsep.join([str(nim_home() / "bin"), env.get("PATH", "")])
    return subprocess.run([str(atlas_exe()), *args], cwd=workspace(root), env=env).returncode


def _git_head(path: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "-C", str(path), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return out.stdout.strip()


def _package_dir(root: Path, pkg: dict) -> Path:
    return workspace(root) / "deps" / pkg.get("dir", pkg["name"])


def _nimble_version(folder: Path) -> str:
    for nimble in sorted(folder.glob("*.nimble")):
        match = re.search(r'^\s*version\s*=\s*"([^"]*)"', nimble.read_text(encoding="utf-8"), re.MULTILINE)
        if match:
            return match.group(1)
    return ""


def lock(root: Path) -> int:
    """Resolve the declared dependencies with atlas and write nimlang.lock.

    Atlas picks the newest versions the requirements allow, so this also
    upgrades; pin a requirement (``"nimpy == 0.2.0"``) to hold it back.
    """
    deps = read_deps(root)
    if not deps:
        return _clear(root)
    folder = _prepare_workspace(root, deps)
    code = run_atlas(root, ["install"])
    if code == 0:
        code = run_atlas(root, ["pin", "atlas.lock"])
    if code != 0:
        return code
    items = json.loads((folder / "atlas.lock").read_text(encoding="utf-8"))["items"]
    packages = []
    for name, item in items.items():
        pkg = {"name": name}
        # atlas writes "$deps\\nimpy" on Windows; the lock always uses "/".
        rel = item["dir"].replace("\\", "/").removeprefix("$deps/")
        if rel != name:
            pkg["dir"] = rel
        pkg["version"] = item.get("version") or _nimble_version(_package_dir(root, pkg))
        pkg["url"] = item["url"]
        pkg["commit"] = item["commit"]
        packages.append(pkg)
    _write_lock(root, deps, packages)
    print(f"nimlang: locked {len(packages)} Nim package(s) in {LOCK_FILE}")
    return 0


def _clear(root: Path) -> int:
    (root / LOCK_FILE).unlink(missing_ok=True)
    (workspace(root) / "nim.cfg").unlink(missing_ok=True)
    print("nimlang: no Nim dependencies declared in [tool.nimlang]")
    return 0


def _in_sync(root: Path, packages: list[dict]) -> bool:
    if not (workspace(root) / "nim.cfg").is_file():
        return False
    return all(_git_head(_package_dir(root, pkg)) == pkg["commit"] for pkg in packages)


def sync(root: Path) -> int:
    """Check out the locked dependencies, resolving first if nimlang.lock is missing or stale."""
    deps = read_deps(root)
    if not deps:
        return _clear(root)
    locked = _read_lock(root)
    if locked is None or locked.get("requires") != deps:
        code = lock(root)
        if code != 0:
            return code
        locked = _read_lock(root)
    packages = locked.get("package", [])
    if _in_sync(root, packages):
        return 0
    folder = _prepare_workspace(root, deps)
    items = {
        pkg["name"]: {
            "dir": f"$deps/{pkg.get('dir', pkg['name'])}",
            "url": pkg["url"],
            "commit": pkg["commit"],
            "version": pkg.get("version", ""),
        }
        for pkg in packages
    }
    (folder / "atlas.lock").write_text(json.dumps({"items": items}, indent=2), encoding="utf-8")
    code = run_atlas(root, ["rep", "atlas.lock"])
    if code != 0:
        return code
    # atlas rep reports a commit it cannot check out but still exits with 0.
    wrong = [pkg["name"] for pkg in packages if _git_head(_package_dir(root, pkg)) != pkg["commit"]]
    if wrong:
        raise NimlangError(f"could not check out the locked commit of: {', '.join(wrong)}")
    return 0


def installed_packages(root: Path) -> dict[str, Path]:
    """Package name -> source directory, from the nim.cfg atlas writes in the workspace."""
    cfg = workspace(root) / "nim.cfg"
    if not cfg.is_file():
        return {}
    found = {}
    for match in re.finditer(r'^--path:"?([^"\n]+)"?\s*$', cfg.read_text(encoding="utf-8"), re.MULTILINE):
        path = (workspace(root) / match.group(1)).resolve()
        rel = Path(match.group(1)).parts
        name = rel[1] if len(rel) > 1 and rel[0] == "deps" else path.name
        found[name.lower()] = path
    return found


def path_args(root: Path | None) -> list[str]:
    """Nim flags exposing exactly this project's Nim dependencies.

    ``--noNimblePath`` hides packages from the global ~/.nimble so builds only
    see what pyproject.toml declares.
    """
    if root is None or not (workspace(root) / "nim.cfg").is_file():
        return []
    return ["--noNimblePath"] + [f"--path:{p}" for p in installed_packages(root).values()]
